name: Build GitHub Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    id-token: write
    contents: write
    pages: write

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
            fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
      - run: pip install \
              'mkdocs-material>=9.5.0,<9.6.0'
      - run: mkdocs build --config-file mkdocs.yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: docs
          publish_dir: site

  deploy_mkdocs:
    needs: build_mkdocs
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
            ref: gh-pages
      - name: Setup Pages
        # A GitHub Action to enable Pages and extract various metadata about a site.
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Upload artifact
        # A composite Action for packaging and uploading artifact that can be deployed to GitHub Pages.
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
            path: '.'
      - name: Deploy to GitHub Pages
        # This action is used to deploy Actions artifacts to GitHub Pages.
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0